require_relative '../components/book'
require_relative '../components/classroom'
require_relative '../components/person'
require_relative '../components/rental'
require_relative '../components/student'
require_relative '../components/teacher'
require_relative '../components/nameable'
require_relative '../interfaces/books_ui'
require_relative '../decorators/base_decorator'
require_relative '../decorators/capitalize_decorator'
require_relative '../decorators/trimmer_decorator'

require 'json'
